baseurl = "http://methane.github.io"
languageCode = "en-us"
title = "Python Bytes"
disqusShortname = "pythonbyte"

[permalinks]
    posts = "/:year/:month/:filename/"

[params]
    twitter = "https://twitter.com/methane"
    github = "https://github.com/methane"
